import React, { useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { LinearGradient } from 'expo-linear-gradient';
import { StatusBar } from 'expo-status-bar';

type Role = 'colaborador' | 'gestor_area' | 'manutencao' | 'custos';
type Manager = Exclude<Role, 'colaborador' | 'gestor_area'>;
type Status = 'pending' | 'review' | 'approved' | 'rejected' | 'in_progress' | 'completed' | 'not_completed';
type Approval = { manager: Manager; approvedAt: string | null };
type Project = { id: string; title: string; description: string; area: string; owner: string; author: string; status: Status; reason: string; comments: string[]; costCents: number; returnCents: number; returnPeriod: 'month' | 'year'; estimateNotes: string; approvals: Approval[]; history: string[] };
const KEY = 'melhorias-offline-finance-v1';
const label: Record<Status, string> = { pending: 'Aguardando gestor da área', review: 'Aguardando gestores', approved: 'Aprovada por todos', rejected: 'Não aprovada', in_progress: 'Em andamento', completed: 'Concluída', not_completed: 'Não concluída' };
const managers: { id: Manager; name: string; password: string }[] = [
  { id: 'manutencao', name: 'Gestor da manutenção', password: '222222' },
  { id: 'custos', name: 'Gestor de custos', password: '333333' },
];
const money = (cents: number) => (cents / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const parseMoney = (value: string) => { const cleaned = value.trim().replace(/\./g, '').replace(',', '.'); return /^\d+(\.\d{1,2})?$/.test(cleaned) ? Math.round(Number(cleaned) * 100) : null; };
const makeId = () => `${Date.now()}-${Math.random()}`;
function Button({ text, onPress, outline = false }: { text: string; onPress: () => void; outline?: boolean }) { return <Pressable onPress={onPress} style={[s.button, outline && s.outline]}><Text style={[s.buttonText, outline && { color: '#2279A9' }]}>{text}</Text></Pressable>; }
function Input({ value, onChange, placeholder, multi = false, secure = false }: { value: string; onChange: (v: string) => void; placeholder: string; multi?: boolean; secure?: boolean }) { return <TextInput value={value} onChangeText={onChange} placeholder={placeholder} multiline={multi} secureTextEntry={secure} style={[s.input, multi && { minHeight: 90, textAlignVertical: 'top' }]} />; }
export default function OfflineApp() {
  const [role, setRole] = useState<Role | null>(null), [selected, setSelected] = useState<Project | null>(null), [items, setItems] = useState<Project[]>([]), [login, setLogin] = useState(''), [show, setShow] = useState(false), [form, setForm] = useState(false), [title, setTitle] = useState(''), [description, setDescription] = useState(''), [area, setArea] = useState(''), [owner, setOwner] = useState(''), [comment, setComment] = useState(''), [reason, setReason] = useState('');
  const [cost, setCost] = useState(''), [expectedReturn, setExpectedReturn] = useState(''), [returnPeriod, setReturnPeriod] = useState<'month' | 'year'>('month'), [estimateNotes, setEstimateNotes] = useState(''), [chosen, setChosen] = useState<Manager[]>([]), [loaded, setLoaded] = useState(false);
  useEffect(() => { AsyncStorage.getItem(KEY).then(raw => setItems(raw ? JSON.parse(raw) : []))
    .catch(() => Alert.alert('Não foi possível carregar as propostas deste aparelho.')).finally(() => setLoaded(true)); }, []);
  useEffect(() => { if (loaded) void AsyncStorage.setItem(KEY, JSON.stringify(items)); }, [items, loaded]);
  const update = (next: Project) => { setItems(current => current.map(item => item.id === next.id ? next : item)); setSelected(next); };
  if (!role) return <SafeAreaView style={s.page}><Header /><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Acesso para teste offline</Text><Text style={s.copy}>Colaborador: 000000 · Gestor da área: 111111</Text><Text style={s.copy}>Manutenção: 222222 · Custos: 333333</Text><Input value={login} onChange={setLogin} placeholder="Senha" secure={!show} /><Pressable onPress={() => setShow(!show)}><Text style={s.link}>{show ? 'Ocultar senha' : 'Mostrar senha'}</Text></Pressable><Button text="Entrar como colaborador" onPress={() => login === '000000' ? setRole('colaborador') : Alert.alert('Senha incorreta')} /><Button text="Entrar como gestor da área" outline onPress={() => login === '111111' ? setRole('gestor_area') : Alert.alert('Senha incorreta')} />{managers.map(manager => <Button key={manager.id} text={`Entrar: ${manager.name}`} outline onPress={() => login === manager.password ? setRole(manager.id) : Alert.alert('Senha incorreta')} />)}</ScrollView></SafeAreaView>;
  if (form) return <SafeAreaView style={s.page}><Header /><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.title}>Nova proposta</Text><Input value={title} onChange={setTitle} placeholder="Título" /><Input value={description} onChange={setDescription} placeholder="Descrição" multi /><Input value={area} onChange={setArea} placeholder="Setor / área" /><Input value={owner} onChange={setOwner} placeholder="Responsável" /><Text style={s.title}>Estimativa financeira</Text><Input value={cost} onChange={setCost} placeholder="Custo de implantação (R$)" /><Input value={expectedReturn} onChange={setExpectedReturn} placeholder="Retorno esperado (R$)" /><Text style={s.copy}>Período informado: {returnPeriod === 'month' ? 'por mês' : 'por ano'}</Text><Button text="Retorno por mês" outline={returnPeriod !== 'month'} onPress={() => setReturnPeriod('month')} /><Button text="Retorno por ano" outline={returnPeriod !== 'year'} onPress={() => setReturnPeriod('year')} /><Input value={estimateNotes} onChange={setEstimateNotes} placeholder="Explique de onde vêm as estimativas" multi /><Button text="Enviar ao gestor da área" onPress={() => { const costCents = parseMoney(cost), returnCents = parseMoney(expectedReturn); if (![title, description, area, owner, estimateNotes].every(value => value.trim()) || costCents === null || costCents <= 0 || returnCents === null) return Alert.alert('Preencha a proposta, custo, retorno e origem das estimativas. O custo deve ser maior que zero.'); setItems([{ id: makeId(), title: title.trim(), description: description.trim(), area: area.trim(), owner: owner.trim(), author: role, status: 'pending', reason: '', comments: [], costCents, returnCents, returnPeriod, estimateNotes: estimateNotes.trim(), approvals: [], history: [`${new Date().toLocaleString('pt-BR')} · Proposta criada`] }, ...items]); setTitle(''); setDescription(''); setArea(''); setOwner(''); setCost(''); setExpectedReturn(''); setEstimateNotes(''); setForm(false); }} /></ScrollView></SafeAreaView>;
  if (selected) {
    const monthly = selected.returnPeriod === 'month' ? selected.returnCents : Math.round(selected.returnCents / 12);
    const annual = selected.returnPeriod === 'year' ? selected.returnCents : selected.returnCents * 12;
    const saveAction = (action: string, changes: Partial<Project>) => update({ ...selected, ...changes, history: [...selected.history, `${new Date().toLocaleString('pt-BR')} · ${role}: ${action}`] });
    const pendingForMe = managers.some(manager => manager.id === role) && selected.approvals.some(approval => approval.manager === role && !approval.approvedAt);
    return <SafeAreaView style={s.page}><Header /><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
      <Pressable onPress={() => setSelected(null)}><Text style={s.link}>‹ Voltar</Text></Pressable>
      <Text style={s.title}>{selected.title}</Text><Text style={s.badge}>{label[selected.status]}</Text>
      <Text style={s.copy}>{selected.area} · Responsável: {selected.owner}</Text><Text style={s.copy}>{selected.description}</Text>
      <View style={s.card}><Text style={s.cardTitle}>Estimativa financeira</Text>
        <Text style={s.copy}>Custo de implantação: {money(selected.costCents)}</Text>
        <Text style={s.copy}>Retorno previsto: {money(monthly)} por mês · {money(annual)} por ano</Text>
        <Text style={s.copy}>Origem da estimativa: {selected.estimateNotes}</Text>
      </View>
      <Text style={s.title}>Aprovações</Text>
      {selected.approvals.length === 0 && <Text style={s.copy}>O gestor da área ainda escolherá os aprovadores.</Text>}
      {selected.approvals.map(approval => <Text key={approval.manager} style={s.copy}>{managers.find(manager => manager.id === approval.manager)?.name}: {approval.approvedAt ? `aprovado em ${approval.approvedAt}` : 'aguardando aprovação'}</Text>)}
      {role === 'gestor_area' && selected.status === 'pending' && <View style={s.card}>
        <Text style={s.cardTitle}>Escolher gestores aprovadores</Text><Text style={s.copy}>Selecione pelo menos dois gestores.</Text>
        {managers.map(manager => <Pressable key={manager.id} onPress={() => setChosen(current => current.includes(manager.id) ? current.filter(id => id !== manager.id) : [...current, manager.id])}><Text style={s.link}>{chosen.includes(manager.id) ? '☑' : '☐'} {manager.name}</Text></Pressable>)}
        <Button text="Enviar para aprovação" onPress={() => { if (chosen.length < 2) return Alert.alert('Escolha pelo menos dois gestores'); saveAction(`Aprovadores definidos: ${chosen.join(', ')}`, { status: 'review', approvals: chosen.map(manager => ({ manager, approvedAt: null })) }); setChosen([]); }} />
      </View>}
      {pendingForMe && selected.status === 'review' && <Button text="Registrar minha aprovação" onPress={() => { const approvals = selected.approvals.map(approval => approval.manager === role ? { ...approval, approvedAt: new Date().toLocaleString('pt-BR') } : approval); saveAction('Aprovação registrada', { approvals, status: approvals.every(approval => approval.approvedAt) ? 'approved' : 'review' }); }} />}
      {role === 'gestor_area' && selected.status === 'approved' && <Button text="Iniciar execução" onPress={() => saveAction('Execução iniciada', { status: 'in_progress' })} />}
      {role === 'gestor_area' && selected.status === 'in_progress' && <><Button text="Concluir proposta" onPress={() => saveAction('Proposta concluída', { status: 'completed' })} /><Input value={reason} onChange={setReason} placeholder="Motivo para não concluir" multi /><Button text="Não concluir" outline onPress={() => { if (!reason.trim()) return Alert.alert('Informe o motivo'); saveAction(`Não concluída: ${reason.trim()}`, { status: 'not_completed', reason: reason.trim() }); setReason(''); }} /></>}
      {selected.reason ? <Text style={s.reason}>Motivo da não conclusão: {selected.reason}</Text> : null}
      <Text style={s.title}>Comentários</Text>{selected.comments.map((value, i) => <Text key={i} style={s.copy}>• {value}</Text>)}
      <Input value={comment} onChange={setComment} placeholder="Adicionar comentário" multi />
      <Button text="Publicar comentário" onPress={() => { if (comment.trim()) { saveAction('Comentário adicionado', { comments: [...selected.comments, `${role}: ${comment.trim()}`] }); setComment(''); } }} />
      <Text style={s.title}>Histórico da proposta</Text>{selected.history.map((entry, i) => <Text key={i} style={s.copy}>{entry}</Text>)}
    </ScrollView></SafeAreaView>;
  }
  return <SafeAreaView style={s.page}><Header /><ScrollView contentContainerStyle={s.content}><View style={s.top}><Text style={s.title}>Painel de melhorias</Text><Pressable onPress={() => { setSelected(null); setForm(false); setRole(null); }}><Text style={s.link}>Sair</Text></Pressable></View><Button text="+ Propor melhoria" onPress={() => setForm(true)} />{items.length === 0 ? <Text style={s.copy}>Nenhuma proposta criada neste aparelho.</Text> : items.map(item => <Pressable style={s.card} key={item.id} onPress={() => setSelected(item)}><Text style={s.cardTitle}>{item.title}</Text><Text style={s.badge}>{label[item.status]}</Text></Pressable>)}</ScrollView></SafeAreaView>;
}
function Header() { return <LinearGradient colors={['#2279A9', '#419978', '#78B32F']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={s.header}><StatusBar style="light" /><Text style={s.brand}>SUA EMPRESA</Text><Text style={s.sub}>Ideias que movem a operação</Text></LinearGradient>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F3F8F7' }, header: { padding: 22 }, brand: { color: 'white', fontSize: 21, fontWeight: '800' }, sub: { color: 'white', marginTop: 4 }, content: { padding: 20, gap: 10 }, title: { color: '#173348', fontSize: 22, fontWeight: '800' }, copy: { color: '#5E7280', lineHeight: 22 }, input: { borderWidth: 1, borderColor: '#DCE0E5', borderRadius: 9, backgroundColor: 'white', padding: 12, fontSize: 16 }, button: { padding: 14, borderRadius: 9, backgroundColor: '#2279A9', alignItems: 'center' }, outline: { backgroundColor: 'white', borderWidth: 1, borderColor: '#2279A9' }, buttonText: { color: 'white', fontWeight: '800' }, link: { color: '#2279A9', fontWeight: '800' }, card: { backgroundColor: 'white', padding: 15, borderRadius: 12 }, cardTitle: { fontWeight: '800', color: '#173348', fontSize: 16 }, badge: { color: '#286637', marginTop: 6, fontWeight: '700' }, reason: { color: '#865A27', backgroundColor: '#FFF6E7', padding: 10, borderRadius: 8 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' } });
