import React, { useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { LinearGradient } from 'expo-linear-gradient';
import { StatusBar } from 'expo-status-bar';

type Role = 'colaborador' | 'supervisor';
type Status = 'pending' | 'approved' | 'rejected' | 'in_progress' | 'completed' | 'not_completed';
type Project = { id: string; title: string; description: string; area: string; owner: string; author: string; status: Status; reason: string; comments: string[] };
const KEY = 'melhorias-offline-v1';
const label: Record<Status, string> = { pending: 'Aguardando aprovação', approved: 'Aprovada', rejected: 'Não aprovada', in_progress: 'Em andamento', completed: 'Concluída', not_completed: 'Não concluída' };
const makeId = () => `${Date.now()}-${Math.random()}`;
function Button({ text, onPress, outline = false }: { text: string; onPress: () => void; outline?: boolean }) { return <Pressable onPress={onPress} style={[s.button, outline && s.outline]}><Text style={[s.buttonText, outline && { color: '#2279A9' }]}>{text}</Text></Pressable>; }
function Input({ value, onChange, placeholder, multi = false, secure = false }: { value: string; onChange: (v: string) => void; placeholder: string; multi?: boolean; secure?: boolean }) { return <TextInput value={value} onChangeText={onChange} placeholder={placeholder} multiline={multi} secureTextEntry={secure} style={[s.input, multi && { minHeight: 90, textAlignVertical: 'top' }]} />; }
export default function OfflineApp() {
  const [role, setRole] = useState<Role | null>(null), [selected, setSelected] = useState<Project | null>(null), [items, setItems] = useState<Project[]>([]), [login, setLogin] = useState(''), [show, setShow] = useState(false), [form, setForm] = useState(false), [title, setTitle] = useState(''), [description, setDescription] = useState(''), [area, setArea] = useState(''), [owner, setOwner] = useState(''), [comment, setComment] = useState(''), [reason, setReason] = useState('');
  useEffect(() => { AsyncStorage.getItem(KEY).then(raw => setItems(raw ? JSON.parse(raw) : [])); }, []);
  useEffect(() => { AsyncStorage.setItem(KEY, JSON.stringify(items)); }, [items]);
  const update = (next: Project) => { setItems(current => current.map(item => item.id === next.id ? next : item)); setSelected(next); };
  if (!role) return <SafeAreaView style={s.page}><Header /><View style={s.content}><Text style={s.title}>Acesso para teste offline</Text><Text style={s.copy}>Colaborador: 111111 · Supervisor: 000000</Text><Input value={login} onChange={setLogin} placeholder="Senha" secure={!show} /><Pressable onPress={() => setShow(!show)}><Text style={s.link}>{show ? 'Ocultar senha' : 'Mostrar senha'}</Text></Pressable><Button text="Entrar como colaborador" onPress={() => login === '111111' ? setRole('colaborador') : Alert.alert('Senha incorreta')} /><Button text="Entrar como supervisor" outline onPress={() => login === '000000' ? setRole('supervisor') : Alert.alert('Senha incorreta')} /></View></SafeAreaView>;
  if (form) return <SafeAreaView style={s.page}><Header /><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Nova proposta</Text><Input value={title} onChange={setTitle} placeholder="Título" /><Input value={description} onChange={setDescription} placeholder="Descrição" multi /><Input value={area} onChange={setArea} placeholder="Setor / área" /><Input value={owner} onChange={setOwner} placeholder="Responsável" /><Button text="Enviar para aprovação" onPress={() => { if (![title, description, area, owner].every(Boolean)) return Alert.alert('Preencha todos os campos'); setItems([{ id: makeId(), title, description, area, owner, author: role, status: 'pending', reason: '', comments: [] }, ...items]); setTitle(''); setDescription(''); setArea(''); setOwner(''); setForm(false); }} /></ScrollView></SafeAreaView>;
  if (selected) return <SafeAreaView style={s.page}><Header /><ScrollView contentContainerStyle={s.content}><Pressable onPress={() => setSelected(null)}><Text style={s.link}>‹ Voltar</Text></Pressable><Text style={s.title}>{selected.title}</Text><Text style={s.badge}>{label[selected.status]}</Text><Text style={s.copy}>{selected.area} · Responsável: {selected.owner}</Text><Text style={s.copy}>{selected.description}</Text>{selected.reason ? <Text style={s.reason}>Motivo da não conclusão: {selected.reason}</Text> : null}{role === 'supervisor' && <><Button text="Aprovar" onPress={() => update({ ...selected, status: 'approved' })} /><Button text="Iniciar execução" onPress={() => update({ ...selected, status: 'in_progress' })} /><Button text="Concluir" onPress={() => update({ ...selected, status: 'completed' })} />{selected.status !== 'completed' && <><Input value={reason} onChange={setReason} placeholder="Motivo para não concluir" multi /><Button text="Não concluir" outline onPress={() => reason ? update({ ...selected, status: 'not_completed', reason }) : Alert.alert('Informe o motivo')} /></>}</>}<Text style={s.title}>Comentários</Text>{selected.comments.map((value, i) => <Text key={i} style={s.copy}>• {value}</Text>)}<Input value={comment} onChange={setComment} placeholder="Adicionar comentário" multi /><Button text="Publicar comentário" onPress={() => { if (comment) { update({ ...selected, comments: [...selected.comments, comment] }); setComment(''); } }} /></ScrollView></SafeAreaView>;
  return <SafeAreaView style={s.page}><Header /><ScrollView contentContainerStyle={s.content}><View style={s.top}><Text style={s.title}>Painel de melhorias</Text><Pressable onPress={() => setRole(null)}><Text style={s.link}>Sair</Text></Pressable></View><Button text="+ Propor melhoria" onPress={() => setForm(true)} />{items.length === 0 ? <Text style={s.copy}>Nenhuma proposta criada neste aparelho.</Text> : items.map(item => <Pressable style={s.card} key={item.id} onPress={() => setSelected(item)}><Text style={s.cardTitle}>{item.title}</Text><Text style={s.badge}>{label[item.status]}</Text></Pressable>)}</ScrollView></SafeAreaView>;
}
function Header() { return <LinearGradient colors={['#2279A9', '#419978', '#78B32F']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={s.header}><StatusBar style="light" /><Text style={s.brand}>SUA EMPRESA</Text><Text style={s.sub}>Ideias que movem a operação</Text></LinearGradient>; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F3F8F7' }, header: { padding: 22 }, brand: { color: 'white', fontSize: 21, fontWeight: '800' }, sub: { color: 'white', marginTop: 4 }, content: { padding: 20, gap: 10 }, title: { color: '#173348', fontSize: 22, fontWeight: '800' }, copy: { color: '#5E7280', lineHeight: 22 }, input: { borderWidth: 1, borderColor: '#DCE0E5', borderRadius: 9, backgroundColor: 'white', padding: 12, fontSize: 16 }, button: { padding: 14, borderRadius: 9, backgroundColor: '#2279A9', alignItems: 'center' }, outline: { backgroundColor: 'white', borderWidth: 1, borderColor: '#2279A9' }, buttonText: { color: 'white', fontWeight: '800' }, link: { color: '#2279A9', fontWeight: '800' }, card: { backgroundColor: 'white', padding: 15, borderRadius: 12 }, cardTitle: { fontWeight: '800', color: '#173348', fontSize: 16 }, badge: { color: '#286637', marginTop: 6, fontWeight: '700' }, reason: { color: '#865A27', backgroundColor: '#FFF6E7', padding: 10, borderRadius: 8 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' } });
